### ISSUE TITLE
After the LXML issue i got this..

### ISSUE THREAD

**Issue by ItsCEED** [Granitosaurus/gosuticker#1]
NameError: name 'Fore' is not defined

Full error:

`Traceback (most recent call last):
  File "/usr/local/bin/ggmt", line 9, in <module>
    load_entry_point('ggmt==0.9.2', 'console_scripts', 'ggmt')()
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ggmt-0.9.2-py3.5.egg/ggmt/cli.py", line 98, in tick
  File "/usr/local/lib/python3.5/dist-packages/ggmt-0.9.2-py3.5.egg/ggmt/cli.py", line 54, in print_match
NameError: name 'Fore' is not defined
`

**Comment by Granitosaurus** [comment]
`colorama` requirement was missing from requirements.txt and setup.py files. 

This has been resolved in the latest commit.
